; ==============================================
; PlatformIO - Voice AI Mini Robot (Edge Impulse)
; ==============================================

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200

; Dùng partition lớn cho AI model
board_build.partitions = huge_app.csv

; Edge Impulse SDK include paths
build_flags = 
    -Ilib
    -Ilib/edge-impulse-sdk
    -Ilib/edge-impulse-sdk/CMSIS/Core/Include
    -Ilib/edge-impulse-sdk/CMSIS/DSP/Include
    -Ilib/edge-impulse-sdk/third_party/flatbuffers/include
    -Ilib/edge-impulse-sdk/third_party/gemmlowp
    -Ilib/edge-impulse-sdk/third_party/ruy
    -DEI_PORTING_ARDUINO=1
    -DEIDSP_USE_CMSIS_DSP=0
    -DEIDSP_LOAD_CMSIS_DSP_SOURCES=0
    -DEI_CLASSIFIER_SLICES_PER_MODEL_WINDOW=4
    -Os

lib_ldf_mode = deep+
upload_speed = 921600
