; ==============================================
; PlatformIO - Voice AI Mini Robot (Edge Impulse)
; ==============================================

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200

; Dùng partition lớn cho AI model
board_build.partitions = huge_app.csv

; Edge Impulse SDK build flags
build_flags = 
    -Ilib
    -Ilib/edge-impulse-sdk
    -Ilib/edge-impulse-sdk/CMSIS/Core/Include
    -Ilib/edge-impulse-sdk/CMSIS/DSP/Include
    -Ilib/edge-impulse-sdk/third_party/flatbuffers/include
    -Ilib/edge-impulse-sdk/third_party/gemmlowp
    -Ilib/edge-impulse-sdk/third_party/ruy
    -Ilib/edge-impulse-sdk/porting/espressif/ESP-NN/include
    -DEI_PORTING_ARDUINO=1
    -DEI_PORTING_ESPRESSIF=0
    -DEIDSP_USE_CMSIS_DSP=0
    -DEIDSP_LOAD_CMSIS_DSP_SOURCES=0
    -DEI_CLASSIFIER_SLICES_PER_MODEL_WINDOW=4
    -DESP_NN
    -Os
    -w

; Compile src/ + Edge Impulse SDK + TFLite model + ESP-NN
build_src_filter =
    +<*>
    +<../lib/edge-impulse-sdk/classifier/*.cpp>
    +<../lib/edge-impulse-sdk/dsp/**/*.cpp>
    +<../lib/edge-impulse-sdk/porting/arduino/*.cpp>
    +<../lib/edge-impulse-sdk/tensorflow/**/*.cc>
    +<../lib/edge-impulse-sdk/tensorflow/**/*.cpp>
    +<../lib/edge-impulse-sdk/CMSIS/NN/**/*.c>
    +<../lib/edge-impulse-sdk/porting/espressif/ESP-NN/src/**/*.c>
    +<../lib/tflite-model/*.cpp>

; Không dùng PlatformIO library system
lib_ldf_mode = off

; Upload settings
upload_speed = 921600
